[12/May/2017 12:04:32] DEBUG [django.db.backends:89] (0.006) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 12:04:32] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 12:07:39] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:07:39] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."username" = %s' - PARAMS = (u'admin',); args=(u'admin',)
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = %s LIMIT 1' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr',); args=(u'f5v4je6psibua3grxj6naiocjy0huejr',)
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:07:47.206387'); args=(u'f5v4je6psibua3grxj6naiocjy0huejr', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:07:47.206387')
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE "django_session"."session_key" = %s' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr',); args=(u'f5v4je6psibua3grxj6naiocjy0huejr',)
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'DELETE FROM "django_session" WHERE "django_session"."session_key" IN (%s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr',); args=(u'f5v4je6psibua3grxj6naiocjy0huejr',)
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "auth_user" SET "last_login" = %s WHERE "auth_user"."id" = %s' - PARAMS = (u'2017-05-12 12:07:47.643508', 1); args=(u'2017-05-12 12:07:47.643508', 1)
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "django_session" SET "session_data" = %s, "expire_date" = %s WHERE "django_session"."session_key" = %s' - PARAMS = (u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:07:47.702340', u'f5v4je6psibua3grxj6naiocjy0huejr'); args=(u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:07:47.702340', u'f5v4je6psibua3grxj6naiocjy0huejr')
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:07:47.702340'); args=(u'f5v4je6psibua3grxj6naiocjy0huejr', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:07:47.702340')
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:07:47.786713'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:07:47.786713')
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:07:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:07:47] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:07:50] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:07:50.499918'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:07:50.499918')
[12/May/2017 12:07:50] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:07:50] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:07:50] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:07:50] INFO [teledm.views:105] Info message!
[12/May/2017 12:07:50] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:07:50] ERROR [teledm.views:107] Error message!
[12/May/2017 12:07:50] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 12:08:00] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:08:00.393815'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:08:00.393815')
[12/May/2017 12:08:00] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:08:04] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 35, in test
    return render_to_response(img, content_type="image/png")
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: <owslib.util.ResponseWrapper object at 0x7fc79789b090>
[12/May/2017 12:11:21] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 12:11:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 12:12:17] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:12:17.366273'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:12:17.366273')
[12/May/2017 12:12:17] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:12:17] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/.local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: test() takes exactly 2 arguments (1 given)
[12/May/2017 12:14:44] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 12:14:44] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 12:14:47] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:14:47.364392'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:14:47.364392')
[12/May/2017 12:14:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:14:58] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:14:58.225469'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:14:58.225469')
[12/May/2017 12:14:58] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:15:10] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:15:10.007521'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:15:10.007521')
[12/May/2017 12:15:10] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:25:19] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:25:19.971786'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:25:19.971786')
[12/May/2017 12:25:19] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:26:03] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:26:03.261738'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:26:03.261738')
[12/May/2017 12:26:03] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:29:16] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:29:16.289414'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:29:16.289414')
[12/May/2017 12:29:16] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:29:53] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:29:53.625815'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:29:53.625815')
[12/May/2017 12:29:53] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:30:12] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:30:12.285946'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:30:12.285946')
[12/May/2017 12:30:12] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:31:33] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:31:33.027133'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:31:33.027133')
[12/May/2017 12:31:33] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:31:43] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:31:43.271865'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:31:43.271865')
[12/May/2017 12:31:43] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:32:30] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:32:30.984407'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:32:30.984407')
[12/May/2017 12:32:30] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:37:48] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:37:48.858673'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:37:48.858673')
[12/May/2017 12:37:48] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:37:48] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:37:48] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:37:48] INFO [teledm.views:105] Info message!
[12/May/2017 12:37:48] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:37:48] ERROR [teledm.views:107] Error message!
[12/May/2017 12:37:48] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 12:38:23] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:38:23.344446'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:38:23.344446')
[12/May/2017 12:38:23] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:38:23] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:38:23] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:38:23] INFO [teledm.views:105] Info message!
[12/May/2017 12:38:23] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:38:23] ERROR [teledm.views:107] Error message!
[12/May/2017 12:38:23] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 12:40:01] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:40:01.973728'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:40:01.973728')
[12/May/2017 12:40:01] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:40:47] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:40:47.032868'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:40:47.032868')
[12/May/2017 12:40:47] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:41:19] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:41:19.526814'); args=('f5v4je6psibua3grxj6naiocjy0huejr', u'2017-05-12 12:41:19.526814')
[12/May/2017 12:41:19] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:41:42] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:41:42] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."username" = %s' - PARAMS = (u'admin',); args=(u'admin',)
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = %s LIMIT 1' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg',); args=(u'oiv391n0vslv6pky4b3pne7mmrzumqjg',)
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:41:49.277182'); args=(u'oiv391n0vslv6pky4b3pne7mmrzumqjg', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:41:49.277182')
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE "django_session"."session_key" = %s' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg',); args=(u'oiv391n0vslv6pky4b3pne7mmrzumqjg',)
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'DELETE FROM "django_session" WHERE "django_session"."session_key" IN (%s)' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg',); args=(u'oiv391n0vslv6pky4b3pne7mmrzumqjg',)
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "auth_user" SET "last_login" = %s WHERE "auth_user"."id" = %s' - PARAMS = (u'2017-05-12 12:41:49.540957', 1); args=(u'2017-05-12 12:41:49.540957', 1)
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "django_session" SET "session_data" = %s, "expire_date" = %s WHERE "django_session"."session_key" = %s' - PARAMS = (u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:41:49.604990', u'oiv391n0vslv6pky4b3pne7mmrzumqjg'); args=(u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:41:49.604990', u'oiv391n0vslv6pky4b3pne7mmrzumqjg')
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:41:49.604990'); args=(u'oiv391n0vslv6pky4b3pne7mmrzumqjg', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:41:49.604990')
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg', u'2017-05-12 12:41:49.685566'); args=('oiv391n0vslv6pky4b3pne7mmrzumqjg', u'2017-05-12 12:41:49.685566')
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:41:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:41:49] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:41:52] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg', u'2017-05-12 12:41:52.263680'); args=('oiv391n0vslv6pky4b3pne7mmrzumqjg', u'2017-05-12 12:41:52.263680')
[12/May/2017 12:41:52] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:42:03] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'oiv391n0vslv6pky4b3pne7mmrzumqjg', u'2017-05-12 12:42:03.398823'); args=('oiv391n0vslv6pky4b3pne7mmrzumqjg', u'2017-05-12 12:42:03.398823')
[12/May/2017 12:42:03] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:44:14] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:44:14] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:44:20] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."username" = %s' - PARAMS = (u'admin',); args=(u'admin',)
[12/May/2017 12:44:20] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = %s LIMIT 1' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr',); args=(u'4vdhziwjoedk1784pjbwszqyqx65pnyr',)
[12/May/2017 12:44:20] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:44:20] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:44:20.911029'); args=(u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:44:20.911029')
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE "django_session"."session_key" = %s' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr',); args=(u'4vdhziwjoedk1784pjbwszqyqx65pnyr',)
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'DELETE FROM "django_session" WHERE "django_session"."session_key" IN (%s)' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr',); args=(u'4vdhziwjoedk1784pjbwszqyqx65pnyr',)
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "auth_user" SET "last_login" = %s WHERE "auth_user"."id" = %s' - PARAMS = (u'2017-05-12 12:44:21.187388', 1); args=(u'2017-05-12 12:44:21.187388', 1)
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "django_session" SET "session_data" = %s, "expire_date" = %s WHERE "django_session"."session_key" = %s' - PARAMS = (u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:44:21.262182', u'4vdhziwjoedk1784pjbwszqyqx65pnyr'); args=(u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:44:21.262182', u'4vdhziwjoedk1784pjbwszqyqx65pnyr')
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:44:21.262182'); args=(u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:44:21.262182')
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:44:21.346467'); args=('4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:44:21.346467')
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:44:21] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:44:21] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:44:22] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:44:22.922464'); args=('4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:44:22.922464')
[12/May/2017 12:44:22] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:44:22] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:44:22] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:44:22] INFO [teledm.views:105] Info message!
[12/May/2017 12:44:22] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:44:22] ERROR [teledm.views:107] Error message!
[12/May/2017 12:44:22] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 12:46:07] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:46:07.920693'); args=('4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:46:07.920693')
[12/May/2017 12:46:07] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:46:07] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:46:07] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:46:07] INFO [teledm.views:105] Info message!
[12/May/2017 12:46:07] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:46:07] ERROR [teledm.views:107] Error message!
[12/May/2017 12:46:07] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 12:47:01] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:47:01.177028'); args=('4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:47:01.177028')
[12/May/2017 12:47:01] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:47:11] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:47:11.317267'); args=('4vdhziwjoedk1784pjbwszqyqx65pnyr', u'2017-05-12 12:47:11.317267')
[12/May/2017 12:47:11] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:47:28] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:47:28] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:47:33] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."username" = %s' - PARAMS = (u'admin',); args=(u'admin',)
[12/May/2017 12:47:33] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = %s LIMIT 1' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv',); args=(u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv',)
[12/May/2017 12:47:33] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:47:33] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:47:33.940445'); args=(u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:47:33.940445')
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE "django_session"."session_key" = %s' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv',); args=(u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv',)
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'DELETE FROM "django_session" WHERE "django_session"."session_key" IN (%s)' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv',); args=(u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv',)
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "auth_user" SET "last_login" = %s WHERE "auth_user"."id" = %s' - PARAMS = (u'2017-05-12 12:47:34.192807', 1); args=(u'2017-05-12 12:47:34.192807', 1)
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "django_session" SET "session_data" = %s, "expire_date" = %s WHERE "django_session"."session_key" = %s' - PARAMS = (u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:47:34.266494', u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv'); args=(u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:47:34.266494', u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv')
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:47:34.266494'); args=(u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:47:34.266494')
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:47:34.353810'); args=('6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:47:34.353810')
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:47:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:47:34] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:47:36] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:47:36.747103'); args=('6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:47:36.747103')
[12/May/2017 12:47:36] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:47:46] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:47:46.133941'); args=('6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:47:46.133941')
[12/May/2017 12:47:46] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:49:11] DEBUG [django.db.backends:89] (0.002) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:49:11.147860'); args=('6zdhgy4o3m7bjbu2mhbrbma7ynjaavdv', u'2017-05-12 12:49:11.147860')
[12/May/2017 12:49:11] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:49:11] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:49:11] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:49:11] INFO [teledm.views:105] Info message!
[12/May/2017 12:49:11] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:49:11] ERROR [teledm.views:107] Error message!
[12/May/2017 12:49:11] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 12:50:19] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:50:19] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."username" = %s' - PARAMS = (u'admin',); args=(u'admin',)
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = %s LIMIT 1' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4',); args=(u'9bno3d0zrh68w7tnqamfefzchji5sgf4',)
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:50:26.447014'); args=(u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'M2Q0NDliOGFjOTg2NTgwMDZkODk0ZGNiMDQ2OTNlMjM1MDJhNTcyYjp7fQ==', u'2017-05-26 12:50:26.447014')
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE "django_session"."session_key" = %s' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4',); args=(u'9bno3d0zrh68w7tnqamfefzchji5sgf4',)
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'DELETE FROM "django_session" WHERE "django_session"."session_key" IN (%s)' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4',); args=(u'9bno3d0zrh68w7tnqamfefzchji5sgf4',)
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "auth_user" SET "last_login" = %s WHERE "auth_user"."id" = %s' - PARAMS = (u'2017-05-12 12:50:26.699909', 1); args=(u'2017-05-12 12:50:26.699909', 1)
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'BEGIN' - PARAMS = (); args=None
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'UPDATE "django_session" SET "session_data" = %s, "expire_date" = %s WHERE "django_session"."session_key" = %s' - PARAMS = (u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:50:26.766567', u'9bno3d0zrh68w7tnqamfefzchji5sgf4'); args=(u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:50:26.766567', u'9bno3d0zrh68w7tnqamfefzchji5sgf4')
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT %s AS "session_key", %s AS "session_data", %s AS "expire_date"' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:50:26.766567'); args=(u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'MTVjYjRmYjZlNmVkYzM2YTc3ZDA2MzdlYjU0YWU5M2VkZjQwYTg2Yjp7Il9hdXRoX3VzZXJfaGFzaCI6ImRmMTBhNzA3NDFiZGI0OWNlMGJlNWFjNjI4Y2JlMmEyMzE0Y2I4MTUiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIxIn0=', u'2017-05-26 12:50:26.766567')
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:50:26.843696'); args=('9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:50:26.843696')
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:50:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT (1) AS "a" FROM "auth_group" INNER JOIN "auth_user_groups" ON ( "auth_group"."id" = "auth_user_groups"."group_id" ) WHERE ("auth_user_groups"."user_id" = %s AND "auth_group"."name" = %s) LIMIT 1' - PARAMS = (1, u'teledm'); args=(1, 'teledm')
[12/May/2017 12:50:26] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:50:29] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:50:29.057791'); args=('9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:50:29.057791')
[12/May/2017 12:50:29] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:50:36] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:50:36.663598'); args=('9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:50:36.663598')
[12/May/2017 12:50:36] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:51:38] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:51:38.139291'); args=('9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:51:38.139291')
[12/May/2017 12:51:38] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:51:42] DEBUG [django.db.backends:89] (0.001) QUERY = u'SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = %s AND "django_session"."expire_date" > %s)' - PARAMS = (u'9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:51:42.405915'); args=('9bno3d0zrh68w7tnqamfefzchji5sgf4', u'2017-05-12 12:51:42.405915')
[12/May/2017 12:51:42] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = %s' - PARAMS = (1,); args=(1,)
[12/May/2017 12:51:56] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 12:51:56] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 12:52:54] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:52:54] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:52:55] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:53:07] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:55:25] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:55:25] INFO [teledm.views:105] Info message!
[12/May/2017 12:55:25] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:55:25] ERROR [teledm.views:107] Error message!
[12/May/2017 12:55:25] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 12:57:24] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:57:24] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 12:57:25] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 12:57:27] DEBUG [teledm.views:104] Debug message!
[12/May/2017 12:57:27] INFO [teledm.views:105] Info message!
[12/May/2017 12:57:27] WARNING [teledm.views:106] Warning message!
[12/May/2017 12:57:27] ERROR [teledm.views:107] Error message!
[12/May/2017 12:57:27] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 13:00:16] DEBUG [teledm.views:104] Debug message!
[12/May/2017 13:00:16] INFO [teledm.views:105] Info message!
[12/May/2017 13:00:16] WARNING [teledm.views:106] Warning message!
[12/May/2017 13:00:16] ERROR [teledm.views:107] Error message!
[12/May/2017 13:00:16] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 13:00:53] DEBUG [teledm.views:104] Debug message!
[12/May/2017 13:00:53] INFO [teledm.views:105] Info message!
[12/May/2017 13:00:53] WARNING [teledm.views:106] Warning message!
[12/May/2017 13:00:53] ERROR [teledm.views:107] Error message!
[12/May/2017 13:00:53] CRITICAL [teledm.views:108] Critical message!
[12/May/2017 13:08:15] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 13:08:15] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 13:08:27] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 13:08:27] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 52, in home
    return render_to_response('teledm/home.html', context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/May/2017 13:18:44] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 13:18:44] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 13:18:49] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 13:24:05] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:24:05] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:24:06] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 13:31:34] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 13:31:34] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 13:32:19] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:32:19] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:32:20] DEBUG [teledm.views:51] this is a debug message!
[12/May/2017 13:32:20] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 52, in home
    return render_to_response('teledm/home.html', context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/May/2017 13:32:45] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 13:32:45] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 13:33:06] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 13:33:06] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 53, in home
    return render_to_response('teledm/home.html', context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'climdata.u-bourgogne.fr/teledm/test/(?P<url>.*)$']
[12/May/2017 13:38:13] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 13:38:13] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 13:38:25] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 13:38:25] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 53, in home
    return render_to_response('teledm/home.html', context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/May/2017 13:38:41] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 13:38:41] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 13:38:43] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 13:38:43] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 53, in home
    return render_to_response('teledm/home.html', context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
[12/May/2017 13:39:16] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 13:39:16] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 13:39:22] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 13:43:33] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:43:33] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:43:36] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 13:43:38] DEBUG [teledm.views:105] Debug message!
[12/May/2017 13:43:38] INFO [teledm.views:106] Info message!
[12/May/2017 13:43:38] WARNING [teledm.views:107] Warning message!
[12/May/2017 13:43:38] ERROR [teledm.views:108] Error message!
[12/May/2017 13:43:38] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 13:44:09] DEBUG [teledm.views:105] Debug message!
[12/May/2017 13:44:09] INFO [teledm.views:106] Info message!
[12/May/2017 13:44:09] WARNING [teledm.views:107] Warning message!
[12/May/2017 13:44:09] ERROR [teledm.views:108] Error message!
[12/May/2017 13:44:09] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 13:46:25] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:46:25] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 13:46:26] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 13:46:35] DEBUG [teledm.views:105] Debug message!
[12/May/2017 13:46:35] INFO [teledm.views:106] Info message!
[12/May/2017 13:46:35] WARNING [teledm.views:107] Warning message!
[12/May/2017 13:46:35] ERROR [teledm.views:108] Error message!
[12/May/2017 13:46:35] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 14:03:49] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:03:49] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:03:50] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:08:12] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:08:12] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:08:13] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:11:40] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:11:40] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:11:40] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:18:59] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:18:59] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:19:00] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:21:30] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:21:30] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:21:31] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:23:27] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:23:27] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:23:29] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:24:03] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:24:03] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:24:04] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:25:42] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:25:42] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:25:43] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:26:38] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:26:38] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:26:40] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:29:36] DEBUG [teledm.views:105] Debug message!
[12/May/2017 14:29:36] INFO [teledm.views:106] Info message!
[12/May/2017 14:29:36] WARNING [teledm.views:107] Warning message!
[12/May/2017 14:29:36] ERROR [teledm.views:108] Error message!
[12/May/2017 14:29:36] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 14:29:52] DEBUG [teledm.views:105] Debug message!
[12/May/2017 14:29:52] INFO [teledm.views:106] Info message!
[12/May/2017 14:29:52] WARNING [teledm.views:107] Warning message!
[12/May/2017 14:29:52] ERROR [teledm.views:108] Error message!
[12/May/2017 14:29:52] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 14:30:06] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:30:06] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 14:30:07] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 14:30:09] DEBUG [teledm.views:105] Debug message!
[12/May/2017 14:30:09] INFO [teledm.views:106] Info message!
[12/May/2017 14:30:09] WARNING [teledm.views:107] Warning message!
[12/May/2017 14:30:09] ERROR [teledm.views:108] Error message!
[12/May/2017 14:30:09] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 14:34:01] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/function URL() {    [native code]}
[12/May/2017 14:35:35] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/function URL() {    [native code]}
[12/May/2017 14:40:17] DEBUG [teledm.views:105] Debug message!
[12/May/2017 14:40:17] INFO [teledm.views:106] Info message!
[12/May/2017 14:40:17] WARNING [teledm.views:107] Warning message!
[12/May/2017 14:40:17] ERROR [teledm.views:108] Error message!
[12/May/2017 14:40:17] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 14:41:23] DEBUG [teledm.views:105] Debug message!
[12/May/2017 14:41:23] INFO [teledm.views:106] Info message!
[12/May/2017 14:41:23] WARNING [teledm.views:107] Warning message!
[12/May/2017 14:41:23] ERROR [teledm.views:108] Error message!
[12/May/2017 14:41:23] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 15:14:00] DEBUG [teledm.views:105] Debug message!
[12/May/2017 15:14:00] INFO [teledm.views:106] Info message!
[12/May/2017 15:14:00] WARNING [teledm.views:107] Warning message!
[12/May/2017 15:14:00] ERROR [teledm.views:108] Error message!
[12/May/2017 15:14:00] CRITICAL [teledm.views:109] Critical message!
[12/May/2017 15:42:25] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 15:42:25] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 15:42:26] DEBUG [teledm.views:52] this is a debug message!
[12/May/2017 15:55:12] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 15:55:12] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 15:57:12] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 39, in test
    resp, content = h.request(url, 'GET', headers = { 'Authorization' : 'Basic ' + auth })
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = 
[12/May/2017 15:59:29] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 39, in test
    resp, content = h.request(url, 'GET', headers = { 'Authorization' : 'Basic ' + auth })
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = 
[12/May/2017 15:59:53] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 15:59:53] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:01:13] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:01:13] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:05:36] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:11:20] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:11:20] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:14:37] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:14:37] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:14:50] DEBUG [teledm.views:62] this is a debug message!
[12/May/2017 16:14:52] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 32, in test
    if request.is_jax():
AttributeError: 'WSGIRequest' object has no attribute 'is_jax'
[12/May/2017 16:15:04] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:15:04] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:15:09] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:17:16] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:21:19] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:21:19] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:21:31] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:21:39] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:21:55] DEBUG [teledm.views:115] Debug message!
[12/May/2017 16:21:55] INFO [teledm.views:116] Info message!
[12/May/2017 16:21:55] WARNING [teledm.views:117] Warning message!
[12/May/2017 16:21:55] ERROR [teledm.views:118] Error message!
[12/May/2017 16:21:55] CRITICAL [teledm.views:119] Critical message!
[12/May/2017 16:22:15] DEBUG [teledm.views:83] Debug message!
[12/May/2017 16:22:15] INFO [teledm.views:84] Info message!
[12/May/2017 16:22:15] WARNING [teledm.views:85] Warning message!
[12/May/2017 16:22:15] ERROR [teledm.views:86] Error message!
[12/May/2017 16:22:15] CRITICAL [teledm.views:87] Critical message!
[12/May/2017 16:22:48] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 38, in test
    resp, content = h.request(url, 'GET', headers = { 'Authorization' : 'Basic ' + auth })
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = satellite/modis/catalog.xml
[12/May/2017 16:23:56] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:23:56] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:24:06] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 38, in test
    resp, content = h.request(url, 'GET', headers = { 'Authorization' : 'Basic ' + auth })
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = satellite/modis/catalog.xml
[12/May/2017 16:24:22] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:24:22] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:24:27] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 38, in test
    resp, content = h.request(url, 'GET', headers = { 'Authorization' : 'Basic ' + auth })
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = s
[12/May/2017 16:24:51] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:24:51] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:25:02] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 38, in test
    resp, content = h.request(url, 'GET', headers = { 'Authorization' : 'Basic ' + auth })
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = s
[12/May/2017 16:25:22] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:25:22] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:25:27] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 38, in test
    resp, content = h.request(url, 'GET', headers = { 'Authorization' : 'Basic ' + auth })
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 1505, in request
    (scheme, authority, request_uri, defrag_uri) = urlnorm(uri)
  File "/home/mers/.local/lib/python2.7/site-packages/httplib2/__init__.py", line 244, in urlnorm
    raise RelativeURIError("Only absolute URIs are allowed. uri = %s" % uri)
RelativeURIError: Only absolute URIs are allowed. uri = satellite/modis/catalog.xml
[12/May/2017 16:26:03] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:26:03] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:43:43] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 16:43:43] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 16:43:45] DEBUG [teledm.views:64] this is a debug message!
[12/May/2017 16:44:01] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:45:31] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:46:41] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:48:27] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 16:48:27] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 16:50:55] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 16:50:55] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 16:50:56] DEBUG [teledm.views:67] this is a debug message!
[12/May/2017 16:51:03] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 16:51:10] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:02:53] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:03:49] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:04:04] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:04:04] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:04:05] DEBUG [teledm.views:67] this is a debug message!
[12/May/2017 17:04:11] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:04:16] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:04:43] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:09:16] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:09:16] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:09:17] DEBUG [teledm.views:67] this is a debug message!
[12/May/2017 17:09:28] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:10:41] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:14:53] DEBUG [teledm.views:120] Debug message!
[12/May/2017 17:14:53] INFO [teledm.views:121] Info message!
[12/May/2017 17:14:53] WARNING [teledm.views:122] Warning message!
[12/May/2017 17:14:53] ERROR [teledm.views:123] Error message!
[12/May/2017 17:14:53] CRITICAL [teledm.views:124] Critical message!
[12/May/2017 17:18:01] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:18:01] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:18:10] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:19:09] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:19:09] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:19:43] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:19:43] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:19:45] DEBUG [teledm.views:68] this is a debug message!
[12/May/2017 17:20:09] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:20:34] DEBUG [teledm.views:121] Debug message!
[12/May/2017 17:20:34] INFO [teledm.views:122] Info message!
[12/May/2017 17:20:34] WARNING [teledm.views:123] Warning message!
[12/May/2017 17:20:34] ERROR [teledm.views:124] Error message!
[12/May/2017 17:20:34] CRITICAL [teledm.views:125] Critical message!
[12/May/2017 17:21:14] WARNING [django.request:98] Forbidden (CSRF token missing or incorrect.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:24:27] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 45, in test
    return render(request, 'index.html', {content})
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: index.html
[12/May/2017 17:25:06] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:25:06] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:25:20] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:25:20] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:25:21] DEBUG [teledm.views:68] this is a debug message!
[12/May/2017 17:25:30] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:25:42] DEBUG [teledm.views:121] Debug message!
[12/May/2017 17:25:42] INFO [teledm.views:122] Info message!
[12/May/2017 17:25:42] WARNING [teledm.views:123] Warning message!
[12/May/2017 17:25:42] ERROR [teledm.views:124] Error message!
[12/May/2017 17:25:42] CRITICAL [teledm.views:125] Critical message!
[12/May/2017 17:25:59] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 44, in test
    return HttpResponse(content, content_type='teledm/test.html', context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/http/response.py", line 340, in __init__
    super(HttpResponse, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'context_instance'
[12/May/2017 17:27:51] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:27:51] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:28:07] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:28:07] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:28:08] DEBUG [teledm.views:68] this is a debug message!
[12/May/2017 17:28:16] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:28:19] DEBUG [teledm.views:121] Debug message!
[12/May/2017 17:28:19] INFO [teledm.views:122] Info message!
[12/May/2017 17:28:19] WARNING [teledm.views:123] Warning message!
[12/May/2017 17:28:19] ERROR [teledm.views:124] Error message!
[12/May/2017 17:28:19] CRITICAL [teledm.views:125] Critical message!
[12/May/2017 17:29:11] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:29:11] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:29:28] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:29:28] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:29:29] DEBUG [teledm.views:68] this is a debug message!
[12/May/2017 17:30:26] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:30:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:32:38] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:32:38] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:32:38] DEBUG [teledm.views:67] this is a debug message!
[12/May/2017 17:32:47] WARNING [django.request:98] Forbidden (CSRF cookie not set.): /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 17:33:23] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:33:23] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:33:24] DEBUG [teledm.views:67] this is a debug message!
[12/May/2017 17:36:07] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:36:07] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:36:17] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:36:17] WARNING [django.request:170] Not Found: /favicon.ico
[12/May/2017 17:36:19] DEBUG [teledm.views:68] this is a debug message!
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-77.6,12.4,24.8,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-77.6,-90,24.8,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-180,-90,-77.6,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=24.8,-90,127.2,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=24.8,12.4,127.2,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-180,12.4,-77.6,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=127.2,-90,229.6,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:36:36] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=127.2,12.4,229.6,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:11] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 17:37:11] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-77.6,-90,24.8,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-77.6,12.4,24.8,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=24.8,-90,127.2,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=24.8,12.4,127.2,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-180,12.4,-77.6,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=-180,-90,-77.6,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=127.2,-90,229.6,12.4&WIDTH=256&HEIGHT=256
[12/May/2017 17:37:26] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/LAYERS=https://climdata.u-bourgogne.fr:8443/thredds/wms/satellite/modis/MYD07/res009/MYD07_r009_d.nc?service=WMS&version=1.3.0&request=GetMap&CRS=CRS%3A84&LAYERS=Surface_Temperature&elevation=Layer&TRANSPARENT=true&FORMAT=image%2Fpng&SRS=EPSG&TRANSPARENT=true&FORMAT=image/png&STYLES=boxfill/rainbow&COLORSCALERANGE=270,350&TIME=2007-01-02&NUMCOLORBANDS=250&OPACITY=100&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&SRS=EPSG:4326&BBOX=127.2,12.4,229.6,114.8&WIDTH=256&HEIGHT=256
[12/May/2017 18:04:07] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:04:07] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:20:38] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mers/dev/crc/crc/urls.py", line 13, in <module>
    url(r'^climdata.u-bourgogne.fr/teledm/', include('teledm.urls', namespace='teledm', app_name='teledm')),
  File "/home/mers/.local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mers/dev/crc/teledm/urls.py", line 23, in <module>
    url(r'^test/(?P<url>.*)$', views.proxy_view, name='test'),
AttributeError: 'module' object has no attribute 'proxy_view'
[12/May/2017 18:21:07] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() got an unexpected keyword argument 'url'
[12/May/2017 18:21:54] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:21:54] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:21:59] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() got an unexpected keyword argument 'wms'
[12/May/2017 18:22:19] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:22:19] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:22:26] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() takes exactly 2 arguments (1 given)
[12/May/2017 18:22:38] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:22:38] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:26:50] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:26:50] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:26:54] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() got an unexpected keyword argument 'wms'
[12/May/2017 18:34:50] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:34:50] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:35:15] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 226, in resolve
    match = self.regex.search(path)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 194, in regex
    (regex, six.text_type(e)))
ImproperlyConfigured: "^test/(?w.*)$" is not a valid regular expression: unexpected end of pattern
[12/May/2017 18:37:20] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:37:20] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:37:23] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 226, in resolve
    match = self.regex.search(path)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 194, in regex
    (regex, six.text_type(e)))
ImproperlyConfigured: "^test/(?P.*)$" is not a valid regular expression: unknown specifier: ?P.
[12/May/2017 18:37:44] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:37:44] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:37:47] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() got an unexpected keyword argument 'wms'
[12/May/2017 18:38:06] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:38:06] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:38:09] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() got an unexpected keyword argument 'thredds'
[12/May/2017 18:38:26] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:38:26] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:38:29] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: test() got an unexpected keyword argument 'test'
[12/May/2017 18:40:27] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:40:27] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:40:47] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 53, in test
    return render_to_response("teledm/test.html", context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'climdata.u-bourgogne.fr/teledm/test/(?P<url>.*)$']
[12/May/2017 18:42:58] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:42:58] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:43:16] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 53, in test
    return render_to_response("teledm/test.html", context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'climdata.u-bourgogne.fr/teledm/test/(?P<path>.*)$']
[12/May/2017 18:48:00] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 53, in test
    return render_to_response("teledm/test.html", context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'climdata.u-bourgogne.fr/teledm/test/(?P<path>.*)$']
[12/May/2017 18:48:55] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:48:55] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:49:00] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 18:50:49] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:50:49] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:50:52] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 18:51:05] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:51:05] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:51:14] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 53, in test
    return render_to_response("teledm/test.html", context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'climdata.u-bourgogne.fr/teledm/test/(?P<path>.*)$']
[12/May/2017 18:51:33] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:51:33] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:51:38] WARNING [django.request:170] Not Found: /climdata.u-bourgogne.fr/teledm/test/
[12/May/2017 18:51:55] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:51:55] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 18:55:19] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 18:55:19] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 19:04:04] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 39, in test
    response = requests.request('GET', url, args)
TypeError: request() takes exactly 2 arguments (3 given)
[12/May/2017 19:04:24] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 19:04:24] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 19:04:43] DEBUG [django.db.backends:89] (0.002) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[12/May/2017 19:04:43] DEBUG [django.db.backends:89] (0.000) QUERY = u'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[12/May/2017 19:04:46] ERROR [django.request:256] Internal Server Error: /climdata.u-bourgogne.fr/teledm/test/
Traceback (most recent call last):
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mers/dev/crc/teledm/views.py", line 64, in test
    return render_to_response("teledm/test.html", context_instance=RequestContext(request))
  File "/home/mers/.local/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/engine.py", line 217, in render_to_string
    return t.render(context_instance)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/home/mers/.local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/home/mers/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'test' with arguments '()' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'climdata.u-bourgogne.fr/teledm/test/(?P<path>.*)$']
